### ISSUE TITLE
1.19.2 - Chat Colours not working

### ISSUE THREAD

**Issue by XionioXMaster** [kangarko/ChatControl-Red#2205]
### "/version ChatControlRed" - plugin version

10.14.9

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

Nope

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10146285/debug.zip)

### Information about the issue/bug

My server is not working changing the colour of the letters in the chat and decorating, which can cause a problem?

![image](https://user-images.githubusercontent.com/86433158/205440140-26589e1a-0818-4c61-9cae-bf02730756c4.png)
![image](https://user-images.githubusercontent.com/86433158/205440147-cbf38c89-7667-4054-8b6f-fff6a8bc0194.png)

Plugins (710: 3DItems, AlonsoTags, BetonQuest, BetterRTP, BoomBox, BossShopPro, ChatBubbles, ChatControlRed, Chunky, Citizens, CMILib, CommandRegions*, ConditionalEvents, CraftEnhance, CustomCrafting, CustomCrops, DeluxeMenus, DiscordSRV, DiscordSRVUtils, Emojis, EpicPluginLib, Essentials, ExcellentCrates, ExcellentEnchants, ExecutableBlocks, FartherViewDistance, GodsEye, GSit, HolographicDisplays, InteractionVisualizer, ItemEffects, ItemsAdder, Jobs, LagAssist, LevelledMobs, LibsDisguises, LoneLibs, LuckPerms, MagicCosmetics, MiniMOTD, ModelEngine, MRPremiumAddons, Multiverse-Core, MythicalRaces, MythicMobs, NBTAPI, NexEngine, nLogin, NoteBlockAPI, Pl-Hide-Pro, PlaceholderAPI, Plan, PlayerAuctions, PlayerProfile, PlayMoreSounds, ProtectionStones, ProtocolLib, RealisticSeasons, SCore, SetSpawn, SkinsRestorer, spark, TAB, TreasureChestX, Vault, VillagerOverhaul, WolfyUtilities, WorldEdit, WorldGuard, XPBorder

**Comment by XionioXMaster** [comment]
![image](https://user-images.githubusercontent.com/86433158/205440843-b9a30b73-c7e0-4c0e-8707-e97ee5cdf4c0.png)
One way when you use send via command it works

**Comment by kangarko** [comment]
Ensure you have the two {chat_color} and {chat_decoration} variables in your format file for chat:

![a](https://i.imgur.com/RGl72z9.png)

If that does not help, try removing Emojis, ItemsAdder and other chat-altering plugins to see if that works and let me know - I want to keep supporting ItemsAdder tho.
