### ISSUE TITLE
1.20: Chat Control Red Pricing

### ISSUE THREAD

**Issue by zikehalil3535** [kangarko/ChatControl-Red#2395]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hello, Im from Turkey and my country is money is very worthless for your country. Can I get a little discount for Chat Control Red

**Comment by kangarko** [comment]
Hey there,

We currently don't offer any more discounts behind the current pricing. If you can't afford the plugin I recommend using ChatControl Free or a free alternative

Matej
