### ISSUE TITLE
double messages

### ISSUE THREAD

**Issue by dalandis** [kangarko/ChatControl-Red#655]
Came back to this problem. But I can't find a solution.
Can you watch it again?
Also found the same issue - https://github.com/kangarko/ChatControl-Red/issues/94

_Originally posted by @dalandis in https://github.com/kangarko/ChatControl-Red/issues/566#issuecomment-775169903_

I also contacted a person who now supports RedisBungee and he says that this is not a problem with RedisBungee

**Comment by kangarko** [comment]
Please dont double post, I replied over your old commit
