### ISSUE TITLE
1.16.5: /msg states Player is not online on this server.

### ISSUE THREAD

**Issue by Skizzles** [kangarko/ChatControl-Red#881]
When using /msg it states Player is not online on this server regardless of being on the same mode on bungee or across network... nowhere is sending /msg properly.

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Debug: https://ufile.io/ij82iz7c

**Comment by kangarko** [comment]
Are you on cracked or premium?

**Comment by Skizzles** [comment]
> Are you on cracked or premium?

Premium

**Comment by kangarko** [comment]
What's the scope of this issue? Is every player being affected or just one player? Does it go away after a restart? I'm traveling this week so unfortunately I'll be sitting down on this by the end of it at min.

**Comment by Skizzles** [comment]
> What's the scope of this issue? Is every player being affected or just one player? Does it go away after a restart? I'm traveling this week so unfortunately I'll be sitting down on this by the end of it at min.

Every player is affected, happens regardless of restart. Not a single player can message others.

**Comment by kangarko** [comment]
Please try using 10.3.2 until I am back. I apology for this.

**Comment by Skizzles** [comment]
I was using 10.3.2 before switching to 10.3.3, I can try it again but I do not feel it will resolve.

**Comment by Skizzles** [comment]
> Please try using 10.3.2 until I am back. I apology for this.

Tried 10.3.2 and it still has issues.

**Comment by kangarko** [comment]
Hey, I'm here, looking into this in about 1-2 days max, I'm very certain we can get this resolved but if not I will refund you and you can keep the plugin in case it gets solved later

**Comment by Skizzles** [comment]
> Hey, I'm here, looking into this in about 1-2 days max, I'm very certain we can get this resolved but if not I will refund you and you can keep the plugin in case it gets solved later

Hey man! Would love to get it worked out. Let me know if anymore details are needed.

**Comment by kangarko** [comment]
@Skizzles please email me, I'll send you a tweaked version in private with some extra debug messages, been having a hard time to reproduce this.

**Comment by kangarko** [comment]
matej@mineacademy.org

**Comment by Skizzles** [comment]
Sent

**Comment by Skizzles** [comment]
@kangarko 

resolved issue, I did a fresh reinstall of Bungee version and restarted proxy.

**Comment by ElBananaa** [comment]
> @kangarko
> 
> resolved issue, I did a fresh reinstall of Bungee version and restarted proxy.

Hey!
Thanks for letting us know about it.
I'll leave this open so Kangarko could take a look at it, just in case he noticed something wrong on his end.

**Comment by kangarko** [comment]
Thanks, sorry about the delays here, I was not able to reproduce this so yeah I assume you had outdated BungeeControl Red since the packet names tend to change between versions, thanks for letting us know.
